#!/usr/bin/env bash
# initiate_new_project managed: update-project-directory v1
set -euo pipefail

ROOT="${1:-$(pwd)}"
OUT="${PROJECT_DIRECTORY_OUT:-$ROOT/docs/generated/project-directory.md}"
MAX_DEPTH="${PROJECT_DIRECTORY_MAX_DEPTH:-3}"
STATUS_FILE="${PROJECT_DIRECTORY_STATUS_FILE:-}"
MANAGED_MARKER="initiate_new_project managed: project-directory"

write_status() {
  if [ -n "$STATUS_FILE" ]; then
    printf '%s\n' "$1" > "$STATUS_FILE"
  fi
}

is_managed_output() {
  [ -f "$OUT" ] && grep -q "$MANAGED_MARKER" "$OUT" 2>/dev/null
}

cd "$ROOT"
mkdir -p "$(dirname "$OUT")"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

exclude_expr=(
  -name .git -o
  -name .DS_Store -o
  -name node_modules -o
  -name data -o
  -name reports -o
  -name cache -o
  -name build -o
  -name dist -o
  -name coverage -o
  -name __pycache__ -o
  -name .pytest_cache -o
  -name .venv -o
  -name venv
)

dir_count="$(
  find . -maxdepth "$MAX_DEPTH" \( "${exclude_expr[@]}" \) -prune -o -type d -print |
    sed '1d' |
    wc -l |
    tr -d ' '
)"

file_count="$(
  find . -maxdepth "$MAX_DEPTH" \( "${exclude_expr[@]}" \) -prune -o -type f -print |
    wc -l |
    tr -d ' '
)"

{
  printf '<!-- initiate_new_project managed: project-directory v1 -->\n'
  printf '# Project Directory Index\n\n'
  printf 'Generated by `scripts/update-project-directory.sh` for quick project orientation.\n\n'
  printf '## Reading Principles\n\n'
  printf -- '- Start with top-level entry files before reading deeper docs.\n'
  printf -- '- Prefer project-specific `AGENTS.md`, `CONTEXT.md`, and `README.md` when present.\n'
  printf -- '- This index shows at most %s levels and excludes noisy generated/data directories.\n\n' "$MAX_DEPTH"
  printf '## Summary\n\n'
  printf -- '- Root: `%s`\n' "$ROOT"
  printf -- '- Max depth: `%s`\n' "$MAX_DEPTH"
  printf -- '- Directories: `%s`\n' "$dir_count"
  printf -- '- Files: `%s`\n\n' "$file_count"
  printf '## Top-Level Entrypoints\n\n'
  find . -maxdepth 1 -type f \
    \( -name 'AGENTS.md' -o -name 'CONTEXT.md' -o -name 'DESIGN.md' -o -name 'FRONTEND.md' -o -name 'PLANS.md' -o -name 'README.md' \) \
    -print |
    sed 's#^\./#- #' |
    sort
  printf '\n## Tree\n\n'
  printf '```text\n'
  find . -maxdepth "$MAX_DEPTH" \( "${exclude_expr[@]}" \) -prune -o -print |
    sed 's#^\./##' |
    sed '/^\.$/d' |
    sort
  printf '```\n'
} > "$tmp"

if [ -f "$OUT" ] && ! is_managed_output; then
  write_status "skipped-unmanaged"
  if [ -z "$STATUS_FILE" ]; then
    printf 'Manual action required: %s exists without managed marker; not overwritten\n' "$OUT" >&2
  fi
  exit 0
fi

if [ ! -f "$OUT" ] || ! cmp -s "$tmp" "$OUT"; then
  mv "$tmp" "$OUT"
  write_status "generated"
  trap - EXIT
else
  write_status "unchanged"
fi
